baseURL = 'https://www.keanjhsu.com'
languageCode = 'en-us'
title = 'NUS Clinical Translational Science Laboratory - Led by Dr. Kean J. HSU'
theme = 'ananke'

[permalinks]
  member = "/about/member/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Clinical"
    url = "/clinical/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 5

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 6

  [[menu.main]]
    name = "Service"
    url = "/service/"
    weight = 7

  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 8
